version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/containers/janus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/packages/release-trigger/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/devcontainers/janus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/lib/pyjanus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/control/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/hello_world/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/network/"
    schedule:
      interval: "weekly"
