version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/containers/janus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/devcontainers/janus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/lib/pyjanus/"
    schedule:
      interval: "weekly"
