version: 2
registries:
  spacelift-private-registry:
    type: terraform-registry
    url: https://app.spacelift.io
    token: ${{ secrets.SPACELIFT_TOKEN }}
updates:
  - package-ecosystem: "docker"
    directory: "/containers/janus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/packages/release-trigger/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/devcontainers/janus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/lib/pyjanus/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    registries:
      - spacelift-private-registry
    directory: "/terraform/control/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    registries:
      - spacelift-private-registry
    directory: "/terraform/stacks/network/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    registries:
      - spacelift-private-registry
    directory: "/terraform/stacks/admin/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    registries:
      - spacelift-private-registry
    directory: "/terraform/modules/github_oidc/"
    schedule:
      interval: "weekly"
