name: 'Docker Semver Publisher'
description: |
  Sets up Docker and Builds the specified Container. Requires registry
  credentials for usage in order to leverage caching.
  Can optionally push image with Semver and SHA Tags

# jscpd:ignore-start
inputs:
  context:
    description: 'Docker Build Context'
    required: true
  platforms:
    description: 'Platforms to Build'
    required: true
    default: 'linux/amd64'
  push:
    description: 'Push images?'
    required: true
    default: false
  repository:
    description: 'Image Repository to use for caching and pushing'
    required: true
  semver_major:
    description: 'Major version to use for pushed semver tags'
    required: false
  semver_minor:
    description: 'Minor version to use for pushed semver tags'
    required: false
  semver_patch:
    description: 'Patch version to use for pushed semver tags'
    required: false
  registry:
    description: 'OCI Registry to use for caching and pushing'
    required: true
  username:
    description: 'OCI Registry Username'
    required: true
  password:
    description: 'OCI Registry Password'
    required: true
  cleanup:
    description: 'Cleanup images after build?'
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set short git commit SHA
      id: git
      shell: bash
      run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_OUTPUT"

    - name: Set container UUID
      id: uuid
      shell: bash
      run: echo "uuid=$(uuidgen -s -n @url -N ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }})" >> "$GITHUB_OUTPUT"

    # jscpd:ignore-end

    - name: Build container
      id: build
      uses: docker/build-push-action@v5
      env:
        DOCKER_BUILDKIT: 1
        BUILDKIT_INLINE_CACHE: 1
      with:
        cache-from: type=registry,ref=${{ inputs.repository }}
        cache-to: type=inline
        context: ${{ inputs.context }}
        outputs: type=docker,dest=${{ github.workspace }}/${{ steps.uuid.outputs.uuid }}.tar
        platforms: ${{ inputs.platforms }}
        push: false

    - name: Load container
      id: load
      shell: bash
      run: |
        docker load -i ${{ github.workspace }}/${{ steps.uuid.outputs.uuid }}.tar
        date
        rm -f ${{ github.workspace }}/${{ steps.uuid.outputs.uuid }}.tar
        date
        docker inspect -f '{{index .Id}}' ${{ steps.build.outputs.imageid }}
        date
        docker inspect -f '{{index .RepoDigests 0}}' ${{ steps.build.outputs.imageid }}
        date
        echo "digest=$(docker inspect -f '{{index .RepoDigests 0}}' ${{ steps.build.outputs.imageid }} | cut -f2 -d@)" >> "$GITHUB_OUTPUT"
        date

    - name: Tag container
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        docker tag ${{ steps.build.outputs.imageid }} ${{ inputs.repository }}:latest
        docker tag ${{ steps.build.outputs.imageid }} ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }}
        docker tag ${{ steps.build.outputs.imageid }} ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}.${{ inputs.semver_patch }}
        docker tag ${{ steps.build.outputs.imageid }} ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}
        docker tag ${{ steps.build.outputs.imageid }} ${{ inputs.repository }}:v${{ inputs.semver_major }}

    - name: Push container
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        docker push ${{ inputs.repository }}:latest
        docker push ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }}
        docker push ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}.${{ inputs.semver_patch }}
        docker push ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}
        docker push ${{ inputs.repository }}:v${{ inputs.semver_major }}

    # jscpd:ignore-start
    - name: Attest
      uses: actions/attest-build-provenance@v1
      id: attest
      if: ${{ inputs.push == 'false' }}
      with:
        subject-name: ${{ inputs.repository }}
        subject-digest: ${{ steps.load.outputs.digest }}
        push-to-registry: false
    # jscpd:ignore-end

    - name: Cleanup container build
      if: ${{ inputs.cleanup == 'true' }}
      shell: bash
      run: |
        docker image rm -f ${{ steps.build.outputs.imageid }} \
          ${{ inputs.repository }}:latest \
          ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} \
          ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}.${{ inputs.semver_patch }} \
          ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }} \
          ${{ inputs.repository }}:v${{ inputs.semver_major }}
        docker builder prune --all --force --verbose
