name: 'Devcontainer Semver Publisher'
description: |
  Sets up Docker and the Devcontainer CLI. Then builds the specified
  devcontainer configuration. Requires registry credentials for usage
  in order to leverage caching. Can optionally push image with Semver
  and SHA Tags

# jscpd:ignore-start
inputs:
  workspace:
    description: 'Devconatiner workspace (dir with .devcontainer or devcontainer.json)'
    required: true
  platforms:
    description: 'Platforms to Build'
    required: true
    default: 'linux/amd64'
  push:
    description: 'Push images?'
    required: true
    default: false
  repository:
    description: 'Image Repository to use for caching and pushing'
    required: true
  semver_major:
    description: 'Major version to use for pushed semver tags'
    required: false
  semver_minor:
    description: 'Minor version to use for pushed semver tags'
    required: false
  semver_patch:
    description: 'Patch version to use for pushed semver tags'
    required: false
  registry:
    description: 'OCI Registry to use for caching and pushing'
    required: true
  username:
    description: 'OCI Registry Username'
    required: true
  password:
    description: 'OCI Registry Password'
    required: true
  cleanup:
    description: 'Cleanup images after build?'
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set short git commit SHA
      id: git
      shell: bash
      run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_OUTPUT"

    - name: Set devcontainer UUID
      id: uuid
      shell: bash
      run: echo "uuid=$(uuidgen -s -n @url -N ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }})" >> "$GITHUB_OUTPUT"

    # jscpd:ignore-end

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@microsoft'

    - name: Cache devcontainers CLI
      id: cache-devcontainers-cli
      uses: actions/cache@v4
      with:
        path: devcontainers-cli-6b04427324f9c27bf7c43f27ce9f0abfb4912f81.tgz
        key: devcontainers-cli-6b04427324f9c27bf7c43f27ce9f0abfb4912f81

    - name: Build devcontainers CLI
      shell: bash
      id: tgz
      if: steps.cache-devcontainers-cli.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/devcontainers/cli.git ${{ runner.temp }}/cli
        cd ${{ runner.temp }}/cli

        git checkout 6b04427324f9c27bf7c43f27ce9f0abfb4912f81

        yarn install --frozen-lockfile
        yarn type-check
        yarn lint
        yarn package

        mv devcontainers-cli-$(jq -r '.version' < package.json).tgz ${{ github.workspace }}/devcontainers-cli-6b04427324f9c27bf7c43f27ce9f0abfb4912f81.tgz

    - name: Install devcontainers CLI
      shell: bash
      run: |
        npm install -g ${{ github.workspace }}/devcontainers-cli-6b04427324f9c27bf7c43f27ce9f0abfb4912f81.tgz

    - name: Build devcontainer
      id: build
      shell: bash
      run: |
        devcontainer build \
          --workspace-folder ${{ inputs.workspace }} \
          --cache-from ${{ inputs.repository }} \
          --cache-to type=inline \
          --platform ${{ inputs.platforms }} \
          --image-name ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} \
          --output type=image,name=${{ inputs.repository }}:${{ steps.git.outputs.short_sha }},push=${{ inputs.push }}

    - name: Retrieve and Tag devcontainer
      id: tag
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        docker pull ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }}

        docker tag ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} ${{ inputs.repository }}:latest
        docker tag ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}.${{ inputs.semver_patch }}
        docker tag ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}
        docker tag ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} ${{ inputs.repository }}:v${{ inputs.semver_major }}

        echo "digest=$(docker inspect -f '{{index .RepoDigests 0}}' ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }} | cut -f2 -d@)" >> "$GITHUB_OUTPUT"

    - name: Push devcontainer
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        docker push ${{ inputs.repository }}:latest
        docker push ${{ inputs.repository }}:${{ steps.git.outputs.short_sha }}
        docker push ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}.${{ inputs.semver_patch }}
        docker push ${{ inputs.repository }}:v${{ inputs.semver_major }}.${{ inputs.semver_minor }}
        docker push ${{ inputs.repository }}:v${{ inputs.semver_major }}

    # jscpd:ignore-start
    - name: Attest
      uses: actions/attest-build-provenance@v1
      id: attest
      if: ${{ inputs.push == 'true' }}
      with:
        subject-name: ${{ inputs.repository }}
        subject-digest: ${{ steps.tag.outputs.digest }}
        push-to-registry: true
    # jscpd:ignore-end
