# This is a workaround for super-linter to ignore the jinja2 syntax in the file
# @generated
---
- name: SSM Drift Control
  vars:
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/ansible/bucket', region=ansible_aws_ssm_region) }}"
    target_hosts: "{{ lookup('ansible.builtin.file', '/etc/hostname') }}.{{ ansible_aws_ssm_region }}.compute.internal"
  ansible.builtin.import_playbook: site.yml
