---
ansible_become: true
ansible_python_interpreter: /usr/bin/python3.10

dpkg_architecture_lookup:
  x86_64: amd64
  aarch64: arm64
  i386: i386
dpkg_architecture: "{{ dpkg_architecture_lookup[ansible_architecture] }}"

node_version: 22.2.0

actions_runner_user: code
actions_runner_group: code
actions_runner_user_home: "/__w"
