# The version of the configuration file format
version: 1
module_version: 0.1.0

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]

tests:
  - name: Role Access
    project_root: examples/role-access

  - name: Service Principal Access
    project_root: examples/service-principal-access
