# The version of the configuration file format
version: 1
module_version: 0.2.3

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]

tests:
  - name: Simple Usage
    project_root: examples/simple-usage
