name: release-trigger CI

on:
  pull_request:
    paths:
      - 'packages/release-trigger/**'
      - '.github/workflows/release-trigger-ci.yml'
      - 'package-lock.json'
      - 'package.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Build release-trigger
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Cache Node Dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            node_modules
            packages/release-trigger/node_modules
          key: ${{ runner.os }}-npm-v4-${{ hashFiles('package-lock.json') }}

      - name: Install Node Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci

      - name: Run Tests
        run: npm test
        working-directory: packages/release-trigger

      - name: Run Lint
        run: npm run lint
        working-directory: packages/release-trigger
