name: release-trigger CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build release-trigger
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            node_modules
            packages/release-trigger/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json,packages/release-trigger/package-lock.json') }}

      - name: Install release-trigger Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: |
          sudo npm install -g npm@9.9.3
          rm -f package-lock.json package.json
          cd packages/release-trigger
          npm install

  test:
    name: Test & Lint release-trigger
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/release-trigger/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json,packages/release-trigger/package-lock.json') }}

      - name: Run Tests
        run: npm test
        working-directory: packages/release-trigger

      - name: Run Lint
        run: npm run lint
        working-directory: packages/release-trigger
