name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '27 21 * * 6'

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - working_directory: terraform/control
            sarif_file: tfsec-control.sarif
          - tfpath: terraform/stacks/hello_world
            sarif_file: tfsec-hello-world.sarif
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          working_directory: ${{ matrix.working_directory }}
          sarif_file: ${{ matrix.sarif_file }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ matrix.sarif_file }}
